name: testing

on:
    pull_request:
        branches: [main, dev]
jobs:
    # Label of the runner job
    runner-job:
        # You must use a Linux environment when using service containers or container jobs
        runs-on: ubuntu-latest

        # Service containers to run with `runner-job`
        services:
            # Label used to access the service container
            postgres:
                # Docker Hub image
                image: postgres
                # Provide the password for postgres
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: forumapi_test
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    # Maps tcp port 5432 on service container to the host
                    - 5432:5432

        steps:
            # Downloads a copy of the code in your repository before running CI tests
            - name: Check out repository code
              uses: actions/checkout@v3

            # Performs a clean installation of all dependencies in the `package.json` file
            # For more information, see https://docs.npmjs.com/cli/ci.html
            - name: Install dependencies
              run: yarn install --frozen=lockfile

            - name: Migrate Database
              env:
                  DATABASE_URL: postgres://postgres:postgres@localhost:5432/forumapi_test
              run: yarn run node-pg-migrate up

            # Runs the tests
            - name: Run tests
              run: yarn test
              env:
                  PGHOST_TEST: postgres
                  PGUSER_TEST: postgres
                  PGDATABASE_TEST: forumapi_test
                  PGPASSWORD_TEST: postgres
                  PGPORT_TEST: 5432
